/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantesystem;

import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author pedro
 */
public class frmCozinha extends javax.swing.JFrame {
    private JTable tabelaPedidos;
    private JScrollPane scrollPane;

    /**
     * Creates new form frmCozinha
     */
    public frmCozinha() {
        initComponents();
        exibirPedidos();
    }

    private void exibirPedidos() {
        String[] colunas = {"ID", "Cliente", "Produtos", "Observações", "Mesa"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        try {
            Connection con = Conexao.getConnection();
            Statement stmt = con.createStatement();
            String sql = "SELECT p.id, c.nome as cliente, p.observacoes, p.mesa FROM pedidos p JOIN cliente c ON p.id_cliente = c.id";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                int idPedido = rs.getInt("id");
                String cliente = rs.getString("cliente");
                String observacoes = rs.getString("observacoes");
                int mesa = rs.getInt("mesa");
                // Buscar produtos do pedido
                Statement stmtProd = con.createStatement();
                ResultSet rsProd = stmtProd.executeQuery("SELECT pr.nome FROM pedido_produto pp JOIN produto pr ON pp.id_produto = pr.id WHERE pp.id_pedido = " + idPedido);
                StringBuilder produtos = new StringBuilder();
                while (rsProd.next()) {
                    if (produtos.length() > 0) produtos.append(", ");
                    produtos.append(rsProd.getString("nome"));
                }
                rsProd.close();
                stmtProd.close();
                modelo.addRow(new Object[]{idPedido, cliente, produtos.toString(), observacoes, mesa});
            }
            con.close();
        } catch (Exception e) {
            modelo.addRow(new Object[]{"Erro", e.getMessage(), "", "", ""});
        }
        if (tabelaPedidos == null) {
            tabelaPedidos = new JTable(modelo);
            scrollPane = new JScrollPane(tabelaPedidos);
            getContentPane().add(scrollPane);
            scrollPane.setBounds(20, 50, 650, 200);
            setLayout(null);
            jLabel1.setBounds(20, 10, 400, 30);
        } else {
            tabelaPedidos.setModel(modelo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Acompanhe os Pedidos em tempo real");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCozinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
