/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantesystem;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JLabel;
import javax.swing.ListCellRenderer;

/**
 *
 * @author alunocmc
 */
public class frmEnvio extends javax.swing.JFrame {
    private int numeroMesa;
    private frmPedido frmPedidoRef;
    private JComboBox<Cliente> comboCliente;
    private JLabel lblCliente;

    /**
     * Creates new form frmEnvio
     */
    public frmEnvio(frmPedido frmPedidoRef, int numeroMesa) {
        this.frmPedidoRef = frmPedidoRef;
        this.numeroMesa = numeroMesa;
        initComponents();
        jComboBox3.setRenderer(new javax.swing.ListCellRenderer<Cliente>() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<? extends Cliente> list, Cliente value, int index, boolean isSelected, boolean cellHasFocus) {
                return new javax.swing.JLabel(value != null ? value.getNome() + " (" + value.getTelefone() + ")" : "");
            }
        });
        carregarClientes();
    }

    private void carregarClientes() {
        try {
            ClienteDAO dao = new ClienteDAO();
            java.util.List<Cliente> clientes = dao.listarTodos();
            jComboBox3.removeAllItems();
            for (Cliente c : clientes) {
                jComboBox3.addItem(c);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar clientes: " + e.getMessage());
        }
    }

    private List<Produto> buscarProdutosPorNomes(String prato, String bebida) {
        List<Produto> produtos = new ArrayList<>();
        try {
            ProdutoDAO dao = new ProdutoDAO();
            for (Produto p : dao.listarTodos()) {
                if (p.getNome().equals(prato) || p.getNome().equals(bebida)) {
                    produtos.add(p);
                }
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao buscar produtos: " + e.getMessage());
        }
        return produtos;
    }

    private Cliente buscarClienteSelecionado() {
        return (Cliente) jComboBox3.getSelectedItem();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String prato = (String) jComboBox1.getSelectedItem();
        String bebida = (String) jComboBox2.getSelectedItem();
        String observacoes = jTextArea1.getText();
        Cliente cliente = buscarClienteSelecionado();
        if (cliente == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um cliente!");
            return;
        }
        List<Produto> produtos = buscarProdutosPorNomes(prato, bebida);
        Pedido pedido = new Pedido(0, cliente, produtos, observacoes, numeroMesa);
        if (frmPedidoRef != null) {
            frmPedidoRef.adicionarPedido(pedido);
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Pedido adicionado!");
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        setTitle("Pedido do Cliente");

        jLabel1.setText("Prato:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Lasanha à bolonhesa", "Espaguete à carbonara", "Risoto de cogumelos", "Nhoque ao pesto", "Fettuccine Alfredo", "Polenta com linguiça", "Berinjela à parmegiana", "Tiramisù", "Canoli siciliano", "Panna cotta" }));

        jLabel2.setText("Bebida:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Vinho Chianti", "Prosecco", "Aperol Spritz", "Negroni", "Limoncello", "Caffè Espresso", "Caffè Macchiato", "San Pellegrino", "H2O", "Coca Cola", "Guaraná", "Coca Cola (Zero)", "Guaraná (Zero)" }));

        jLabel3.setText("Observações:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEnvio(null, 1).setVisible(true); // Exemplo: abre com mesa 1
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<Cliente> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
